export declare const argent: string;
export declare const award: string;
export declare const body: string;
export declare const container: string;
export declare const date: string;
export declare const khaki: string;
export declare const li: string;
export declare const separator: string;
export declare const smokyBlack: string;
